name: Add Song
description: Add a new song to your practice list
title: "[New Song]: "
labels: ["new-song"]
body:
  - type: input
    id: song_title
    attributes:
      label: Song Title
      placeholder: e.g. Blackbird
    validations:
      required: true
  - type: input
    id: artist_name
    attributes:
      label: Artist
      placeholder: e.g. The Beatles
    validations:
      required: true
  - type: dropdown
    id: song_category
    attributes:
      label: Category
      options:
        - acoustic
        - electric
    validations:
      required: true
