name: Add Song
description: Add a new song to your practice list
title: "[New Song]: "
labels: ["new-song"]
body:
  - type: input
    id: song_title
    attributes:
      label: Song Title
      placeholder: e.g. Blackbird
    validations:
      required: true
  - type: input
    id: artist_name
    attributes:
      label: Artist
      placeholder: e.g. The Beatles
    validations:
      required: true
  - type: input
    id: song_category
    attributes:
      label: Category
      placeholder: acoustic or electric
    validations:
      required: true
  - type: input
    id: song_youtube
    attributes:
      label: YouTube Link
      placeholder: https://www.youtube.com/watch?v=...
  - type: input
    id: song_notes
    attributes:
      label: Notes
      placeholder: e.g. Tuning, difficulty, etc.
